/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyDslGrammarAccess extends AbstractGrammarElementFinder {
	
	public class AssociationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Association");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAssociationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cUsedKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cUsedAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cUsedRoleCrossReference_3_0 = (CrossReference)cUsedAssignment_3.eContents().get(0);
		private final RuleCall cUsedRoleEStringParserRuleCall_3_0_1 = (RuleCall)cUsedRoleCrossReference_3_0.eContents().get(1);
		private final Keyword cUserKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cUserAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cUserRoleCrossReference_5_0 = (CrossReference)cUserAssignment_5.eContents().get(0);
		private final RuleCall cUserRoleEStringParserRuleCall_5_0_1 = (RuleCall)cUserRoleCrossReference_5_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Association:
		//	'Association'
		//	'{'
		//	'used' used=[Role|EString]
		//	'user' user=[Role|EString]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Association' '{' 'used' used=[Role|EString] 'user' user=[Role|EString] '}'
		public Group getGroup() { return cGroup; }
		
		//'Association'
		public Keyword getAssociationKeyword_0() { return cAssociationKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'used'
		public Keyword getUsedKeyword_2() { return cUsedKeyword_2; }
		
		//used=[Role|EString]
		public Assignment getUsedAssignment_3() { return cUsedAssignment_3; }
		
		//[Role|EString]
		public CrossReference getUsedRoleCrossReference_3_0() { return cUsedRoleCrossReference_3_0; }
		
		//EString
		public RuleCall getUsedRoleEStringParserRuleCall_3_0_1() { return cUsedRoleEStringParserRuleCall_3_0_1; }
		
		//'user'
		public Keyword getUserKeyword_4() { return cUserKeyword_4; }
		
		//user=[Role|EString]
		public Assignment getUserAssignment_5() { return cUserAssignment_5; }
		
		//[Role|EString]
		public CrossReference getUserRoleCrossReference_5_0() { return cUserRoleCrossReference_5_0; }
		
		//EString
		public RuleCall getUserRoleEStringParserRuleCall_5_0_1() { return cUserRoleEStringParserRuleCall_5_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class TypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Type");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cType_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cFloatParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cInt0ParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cBooleanParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cString0ParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//Type:
		//	Type_Impl | Float | Int0 | Boolean | String0;
		@Override public ParserRule getRule() { return rule; }
		
		//Type_Impl | Float | Int0 | Boolean | String0
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Type_Impl
		public RuleCall getType_ImplParserRuleCall_0() { return cType_ImplParserRuleCall_0; }
		
		//Float
		public RuleCall getFloatParserRuleCall_1() { return cFloatParserRuleCall_1; }
		
		//Int0
		public RuleCall getInt0ParserRuleCall_2() { return cInt0ParserRuleCall_2; }
		
		//Boolean
		public RuleCall getBooleanParserRuleCall_3() { return cBooleanParserRuleCall_3; }
		
		//String0
		public RuleCall getString0ParserRuleCall_4() { return cString0ParserRuleCall_4; }
	}
	public class RoleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Role");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRoleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cUpperKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cUpperAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cUpperEIntParserRuleCall_3_0 = (RuleCall)cUpperAssignment_3.eContents().get(0);
		private final Keyword cLowerKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cLowerAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cLowerEIntParserRuleCall_5_0 = (RuleCall)cLowerAssignment_5.eContents().get(0);
		private final Keyword cClassKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cClassAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cClassClassCrossReference_7_0 = (CrossReference)cClassAssignment_7.eContents().get(0);
		private final RuleCall cClassClassEStringParserRuleCall_7_0_1 = (RuleCall)cClassClassCrossReference_7_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Role:
		//	'Role'
		//	'{'
		//	'upper' upper=EInt
		//	'lower' lower=EInt
		//	'class' class=[Class|EString]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Role' '{' 'upper' upper=EInt 'lower' lower=EInt 'class' class=[Class|EString] '}'
		public Group getGroup() { return cGroup; }
		
		//'Role'
		public Keyword getRoleKeyword_0() { return cRoleKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'upper'
		public Keyword getUpperKeyword_2() { return cUpperKeyword_2; }
		
		//upper=EInt
		public Assignment getUpperAssignment_3() { return cUpperAssignment_3; }
		
		//EInt
		public RuleCall getUpperEIntParserRuleCall_3_0() { return cUpperEIntParserRuleCall_3_0; }
		
		//'lower'
		public Keyword getLowerKeyword_4() { return cLowerKeyword_4; }
		
		//lower=EInt
		public Assignment getLowerAssignment_5() { return cLowerAssignment_5; }
		
		//EInt
		public RuleCall getLowerEIntParserRuleCall_5_0() { return cLowerEIntParserRuleCall_5_0; }
		
		//'class'
		public Keyword getClassKeyword_6() { return cClassKeyword_6; }
		
		//class=[Class|EString]
		public Assignment getClassAssignment_7() { return cClassAssignment_7; }
		
		//[Class|EString]
		public CrossReference getClassClassCrossReference_7_0() { return cClassClassCrossReference_7_0; }
		
		//EString
		public RuleCall getClassClassEStringParserRuleCall_7_0_1() { return cClassClassEStringParserRuleCall_7_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class ClassElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Class");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cClassAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cClassKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cMethodKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cMethodAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cMethodMethodCrossReference_4_2_0 = (CrossReference)cMethodAssignment_4_2.eContents().get(0);
		private final RuleCall cMethodMethodEStringParserRuleCall_4_2_0_1 = (RuleCall)cMethodMethodCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cMethodAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cMethodMethodCrossReference_4_3_1_0 = (CrossReference)cMethodAssignment_4_3_1.eContents().get(0);
		private final RuleCall cMethodMethodEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cMethodMethodCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cAttributeKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cAttributeAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cAttributeTypeCrossReference_5_2_0 = (CrossReference)cAttributeAssignment_5_2.eContents().get(0);
		private final RuleCall cAttributeTypeEStringParserRuleCall_5_2_0_1 = (RuleCall)cAttributeTypeCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cAttributeAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cAttributeTypeCrossReference_5_3_1_0 = (CrossReference)cAttributeAssignment_5_3_1.eContents().get(0);
		private final RuleCall cAttributeTypeEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cAttributeTypeCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Class:
		//	{Class}
		//	'Class'
		//	name=EString
		//	'{' ('method' '(' method+=[Method|EString] ("," method+=[Method|EString])* ')')? ('attribute' '('
		//	attribute+=[Type|EString] ("," attribute+=[Type|EString])* ')')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Class} 'Class' name=EString '{' ('method' '(' method+=[Method|EString] ("," method+=[Method|EString])* ')')?
		//('attribute' '(' attribute+=[Type|EString] ("," attribute+=[Type|EString])* ')')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Class}
		public Action getClassAction_0() { return cClassAction_0; }
		
		//'Class'
		public Keyword getClassKeyword_1() { return cClassKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('method' '(' method+=[Method|EString] ("," method+=[Method|EString])* ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'method'
		public Keyword getMethodKeyword_4_0() { return cMethodKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//method+=[Method|EString]
		public Assignment getMethodAssignment_4_2() { return cMethodAssignment_4_2; }
		
		//[Method|EString]
		public CrossReference getMethodMethodCrossReference_4_2_0() { return cMethodMethodCrossReference_4_2_0; }
		
		//EString
		public RuleCall getMethodMethodEStringParserRuleCall_4_2_0_1() { return cMethodMethodEStringParserRuleCall_4_2_0_1; }
		
		//("," method+=[Method|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//method+=[Method|EString]
		public Assignment getMethodAssignment_4_3_1() { return cMethodAssignment_4_3_1; }
		
		//[Method|EString]
		public CrossReference getMethodMethodCrossReference_4_3_1_0() { return cMethodMethodCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getMethodMethodEStringParserRuleCall_4_3_1_0_1() { return cMethodMethodEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//('attribute' '(' attribute+=[Type|EString] ("," attribute+=[Type|EString])* ')')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'attribute'
		public Keyword getAttributeKeyword_5_0() { return cAttributeKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//attribute+=[Type|EString]
		public Assignment getAttributeAssignment_5_2() { return cAttributeAssignment_5_2; }
		
		//[Type|EString]
		public CrossReference getAttributeTypeCrossReference_5_2_0() { return cAttributeTypeCrossReference_5_2_0; }
		
		//EString
		public RuleCall getAttributeTypeEStringParserRuleCall_5_2_0_1() { return cAttributeTypeEStringParserRuleCall_5_2_0_1; }
		
		//("," attribute+=[Type|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//attribute+=[Type|EString]
		public Assignment getAttributeAssignment_5_3_1() { return cAttributeAssignment_5_3_1; }
		
		//[Type|EString]
		public CrossReference getAttributeTypeCrossReference_5_3_1_0() { return cAttributeTypeCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getAttributeTypeEStringParserRuleCall_5_3_1_0_1() { return cAttributeTypeEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt ecore::EInt:
		//	'-'? INT
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class MethodElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Method");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMethodAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMethodKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cParametersKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cParametersAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cParametersTypeCrossReference_4_2_0 = (CrossReference)cParametersAssignment_4_2.eContents().get(0);
		private final RuleCall cParametersTypeEStringParserRuleCall_4_2_0_1 = (RuleCall)cParametersTypeCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cParametersAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cParametersTypeCrossReference_4_3_1_0 = (CrossReference)cParametersAssignment_4_3_1.eContents().get(0);
		private final RuleCall cParametersTypeEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cParametersTypeCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cReturnKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cReturnAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cReturnTypeCrossReference_5_1_0 = (CrossReference)cReturnAssignment_5_1.eContents().get(0);
		private final RuleCall cReturnTypeEStringParserRuleCall_5_1_0_1 = (RuleCall)cReturnTypeCrossReference_5_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Method:
		//	{Method}
		//	'Method'
		//	name=EString
		//	'{' ('parameters' '(' parameters+=[Type|EString] ("," parameters+=[Type|EString])* ')')? ('return'
		//	return=[Type|EString])?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Method} 'Method' name=EString '{' ('parameters' '(' parameters+=[Type|EString] ("," parameters+=[Type|EString])* ')')?
		//('return' return=[Type|EString])? '}'
		public Group getGroup() { return cGroup; }
		
		//{Method}
		public Action getMethodAction_0() { return cMethodAction_0; }
		
		//'Method'
		public Keyword getMethodKeyword_1() { return cMethodKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('parameters' '(' parameters+=[Type|EString] ("," parameters+=[Type|EString])* ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'parameters'
		public Keyword getParametersKeyword_4_0() { return cParametersKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//parameters+=[Type|EString]
		public Assignment getParametersAssignment_4_2() { return cParametersAssignment_4_2; }
		
		//[Type|EString]
		public CrossReference getParametersTypeCrossReference_4_2_0() { return cParametersTypeCrossReference_4_2_0; }
		
		//EString
		public RuleCall getParametersTypeEStringParserRuleCall_4_2_0_1() { return cParametersTypeEStringParserRuleCall_4_2_0_1; }
		
		//("," parameters+=[Type|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//parameters+=[Type|EString]
		public Assignment getParametersAssignment_4_3_1() { return cParametersAssignment_4_3_1; }
		
		//[Type|EString]
		public CrossReference getParametersTypeCrossReference_4_3_1_0() { return cParametersTypeCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getParametersTypeEStringParserRuleCall_4_3_1_0_1() { return cParametersTypeEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//('return' return=[Type|EString])?
		public Group getGroup_5() { return cGroup_5; }
		
		//'return'
		public Keyword getReturnKeyword_5_0() { return cReturnKeyword_5_0; }
		
		//return=[Type|EString]
		public Assignment getReturnAssignment_5_1() { return cReturnAssignment_5_1; }
		
		//[Type|EString]
		public CrossReference getReturnTypeCrossReference_5_1_0() { return cReturnTypeCrossReference_5_1_0; }
		
		//EString
		public RuleCall getReturnTypeEStringParserRuleCall_5_1_0_1() { return cReturnTypeEStringParserRuleCall_5_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class Type_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Type_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTypeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTypeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Type_Impl Type:
		//	{Type}
		//	'Type'
		@Override public ParserRule getRule() { return rule; }
		
		//{Type} 'Type'
		public Group getGroup() { return cGroup; }
		
		//{Type}
		public Action getTypeAction_0() { return cTypeAction_0; }
		
		//'Type'
		public Keyword getTypeKeyword_1() { return cTypeKeyword_1; }
	}
	public class FloatElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Float");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFloatKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cValueKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cValueAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cValueEFloatParserRuleCall_3_0 = (RuleCall)cValueAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Float:
		//	'Float'
		//	'{'
		//	'value' value=EFloat
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Float' '{' 'value' value=EFloat '}'
		public Group getGroup() { return cGroup; }
		
		//'Float'
		public Keyword getFloatKeyword_0() { return cFloatKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'value'
		public Keyword getValueKeyword_2() { return cValueKeyword_2; }
		
		//value=EFloat
		public Assignment getValueAssignment_3() { return cValueAssignment_3; }
		
		//EFloat
		public RuleCall getValueEFloatParserRuleCall_3_0() { return cValueEFloatParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class Int0Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Int0");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cIntKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cValueKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cValueAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cValueEIntParserRuleCall_3_0 = (RuleCall)cValueAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Int0 Int:
		//	'Int'
		//	'{'
		//	'value' value=EInt
		//	'}'
		@Override public ParserRule getRule() { return rule; }
		
		//'Int' '{' 'value' value=EInt '}'
		public Group getGroup() { return cGroup; }
		
		//'Int'
		public Keyword getIntKeyword_0() { return cIntKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'value'
		public Keyword getValueKeyword_2() { return cValueKeyword_2; }
		
		//value=EInt
		public Assignment getValueAssignment_3() { return cValueAssignment_3; }
		
		//EInt
		public RuleCall getValueEIntParserRuleCall_3_0() { return cValueEIntParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class BooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Boolean");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cValueAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cValueValueKeyword_0_0 = (Keyword)cValueAssignment_0.eContents().get(0);
		private final Keyword cBooleanKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Boolean:
		//	value?='value'
		//	'Boolean';
		@Override public ParserRule getRule() { return rule; }
		
		//value?='value' 'Boolean'
		public Group getGroup() { return cGroup; }
		
		//value?='value'
		public Assignment getValueAssignment_0() { return cValueAssignment_0; }
		
		//'value'
		public Keyword getValueValueKeyword_0_0() { return cValueValueKeyword_0_0; }
		
		//'Boolean'
		public Keyword getBooleanKeyword_1() { return cBooleanKeyword_1; }
	}
	public class String0Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.String0");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStringKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cValueKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cValueAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cValueEStringParserRuleCall_3_0 = (RuleCall)cValueAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//String0 String:
		//	'String'
		//	'{'
		//	'value' value=EString
		//	'}'
		@Override public ParserRule getRule() { return rule; }
		
		//'String' '{' 'value' value=EString '}'
		public Group getGroup() { return cGroup; }
		
		//'String'
		public Keyword getStringKeyword_0() { return cStringKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'value'
		public Keyword getValueKeyword_2() { return cValueKeyword_2; }
		
		//value=EString
		public Assignment getValueAssignment_3() { return cValueAssignment_3; }
		
		//EString
		public RuleCall getValueEStringParserRuleCall_3_0() { return cValueEStringParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class EFloatElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EFloat");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cEKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		
		//EFloat ecore::EFloat:
		//	'-'? INT? '.' INT (('E' | 'e') '-'? INT)?
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT? '.' INT (('E' | 'e') '-'? INT)?
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT?
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }
		
		//(('E' | 'e') '-'? INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//('E' | 'e')
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }
		
		//'E'
		public Keyword getEKeyword_4_0_0() { return cEKeyword_4_0_0; }
		
		//'e'
		public Keyword getEKeyword_4_0_1() { return cEKeyword_4_0_1; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_4_1() { return cHyphenMinusKeyword_4_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4_2() { return cINTTerminalRuleCall_4_2; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean ecore::EBoolean:
		//	'true' | 'false'
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	
	
	private final AssociationElements pAssociation;
	private final TypeElements pType;
	private final RoleElements pRole;
	private final ClassElements pClass;
	private final EIntElements pEInt;
	private final EStringElements pEString;
	private final MethodElements pMethod;
	private final Type_ImplElements pType_Impl;
	private final FloatElements pFloat;
	private final Int0Elements pInt0;
	private final BooleanElements pBoolean;
	private final String0Elements pString0;
	private final EFloatElements pEFloat;
	private final EBooleanElements pEBoolean;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pAssociation = new AssociationElements();
		this.pType = new TypeElements();
		this.pRole = new RoleElements();
		this.pClass = new ClassElements();
		this.pEInt = new EIntElements();
		this.pEString = new EStringElements();
		this.pMethod = new MethodElements();
		this.pType_Impl = new Type_ImplElements();
		this.pFloat = new FloatElements();
		this.pInt0 = new Int0Elements();
		this.pBoolean = new BooleanElements();
		this.pString0 = new String0Elements();
		this.pEFloat = new EFloatElements();
		this.pEBoolean = new EBooleanElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Association:
	//	'Association'
	//	'{'
	//	'used' used=[Role|EString]
	//	'user' user=[Role|EString]
	//	'}';
	public AssociationElements getAssociationAccess() {
		return pAssociation;
	}
	
	public ParserRule getAssociationRule() {
		return getAssociationAccess().getRule();
	}
	
	//Type:
	//	Type_Impl | Float | Int0 | Boolean | String0;
	public TypeElements getTypeAccess() {
		return pType;
	}
	
	public ParserRule getTypeRule() {
		return getTypeAccess().getRule();
	}
	
	//Role:
	//	'Role'
	//	'{'
	//	'upper' upper=EInt
	//	'lower' lower=EInt
	//	'class' class=[Class|EString]
	//	'}';
	public RoleElements getRoleAccess() {
		return pRole;
	}
	
	public ParserRule getRoleRule() {
		return getRoleAccess().getRule();
	}
	
	//Class:
	//	{Class}
	//	'Class'
	//	name=EString
	//	'{' ('method' '(' method+=[Method|EString] ("," method+=[Method|EString])* ')')? ('attribute' '('
	//	attribute+=[Type|EString] ("," attribute+=[Type|EString])* ')')?
	//	'}';
	public ClassElements getClassAccess() {
		return pClass;
	}
	
	public ParserRule getClassRule() {
		return getClassAccess().getRule();
	}
	
	//EInt ecore::EInt:
	//	'-'? INT
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Method:
	//	{Method}
	//	'Method'
	//	name=EString
	//	'{' ('parameters' '(' parameters+=[Type|EString] ("," parameters+=[Type|EString])* ')')? ('return'
	//	return=[Type|EString])?
	//	'}';
	public MethodElements getMethodAccess() {
		return pMethod;
	}
	
	public ParserRule getMethodRule() {
		return getMethodAccess().getRule();
	}
	
	//Type_Impl Type:
	//	{Type}
	//	'Type'
	public Type_ImplElements getType_ImplAccess() {
		return pType_Impl;
	}
	
	public ParserRule getType_ImplRule() {
		return getType_ImplAccess().getRule();
	}
	
	//Float:
	//	'Float'
	//	'{'
	//	'value' value=EFloat
	//	'}';
	public FloatElements getFloatAccess() {
		return pFloat;
	}
	
	public ParserRule getFloatRule() {
		return getFloatAccess().getRule();
	}
	
	//Int0 Int:
	//	'Int'
	//	'{'
	//	'value' value=EInt
	//	'}'
	public Int0Elements getInt0Access() {
		return pInt0;
	}
	
	public ParserRule getInt0Rule() {
		return getInt0Access().getRule();
	}
	
	//Boolean:
	//	value?='value'
	//	'Boolean';
	public BooleanElements getBooleanAccess() {
		return pBoolean;
	}
	
	public ParserRule getBooleanRule() {
		return getBooleanAccess().getRule();
	}
	
	//String0 String:
	//	'String'
	//	'{'
	//	'value' value=EString
	//	'}'
	public String0Elements getString0Access() {
		return pString0;
	}
	
	public ParserRule getString0Rule() {
		return getString0Access().getRule();
	}
	
	//EFloat ecore::EFloat:
	//	'-'? INT? '.' INT (('E' | 'e') '-'? INT)?
	public EFloatElements getEFloatAccess() {
		return pEFloat;
	}
	
	public ParserRule getEFloatRule() {
		return getEFloatAccess().getRule();
	}
	
	//EBoolean ecore::EBoolean:
	//	'true' | 'false'
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
