/*
 * generated by Xtext 2.10.0
 */
package org.smalluml.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class SmallUMLGrammarAccess extends AbstractGrammarElementFinder {
	
	public class DiagramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUML.Diagram");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDiagramAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cDiagramKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cAssocKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cAssocAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cAssocAssociationParserRuleCall_3_2_0 = (RuleCall)cAssocAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cAssocAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cAssocAssociationParserRuleCall_3_3_1_0 = (RuleCall)cAssocAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cHeritageKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cHeritageAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cHeritageHeritageParserRuleCall_4_2_0 = (RuleCall)cHeritageAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cHeritageAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cHeritageHeritageParserRuleCall_4_3_1_0 = (RuleCall)cHeritageAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cClassKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cClassAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cClassClassParserRuleCall_5_2_0 = (RuleCall)cClassAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cClassAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cClassClassParserRuleCall_5_3_1_0 = (RuleCall)cClassAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Diagram:
		//	{Diagram}
		//	'Diagram'
		//	'{' ('assoc' '{' assoc+=Association ("," assoc+=Association)* '}')? ('heritage' '{' heritage+=Heritage (","
		//	heritage+=Heritage)* '}')? ('class' '{' class+=Class ("," class+=Class)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Diagram} 'Diagram' '{' ('assoc' '{' assoc+=Association ("," assoc+=Association)* '}')? ('heritage' '{'
		//heritage+=Heritage ("," heritage+=Heritage)* '}')? ('class' '{' class+=Class ("," class+=Class)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Diagram}
		public Action getDiagramAction_0() { return cDiagramAction_0; }
		
		//'Diagram'
		public Keyword getDiagramKeyword_1() { return cDiagramKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('assoc' '{' assoc+=Association ("," assoc+=Association)* '}')?
		public Group getGroup_3() { return cGroup_3; }
		
		//'assoc'
		public Keyword getAssocKeyword_3_0() { return cAssocKeyword_3_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }
		
		//assoc+=Association
		public Assignment getAssocAssignment_3_2() { return cAssocAssignment_3_2; }
		
		//Association
		public RuleCall getAssocAssociationParserRuleCall_3_2_0() { return cAssocAssociationParserRuleCall_3_2_0; }
		
		//("," assoc+=Association)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//assoc+=Association
		public Assignment getAssocAssignment_3_3_1() { return cAssocAssignment_3_3_1; }
		
		//Association
		public RuleCall getAssocAssociationParserRuleCall_3_3_1_0() { return cAssocAssociationParserRuleCall_3_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }
		
		//('heritage' '{' heritage+=Heritage ("," heritage+=Heritage)* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'heritage'
		public Keyword getHeritageKeyword_4_0() { return cHeritageKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//heritage+=Heritage
		public Assignment getHeritageAssignment_4_2() { return cHeritageAssignment_4_2; }
		
		//Heritage
		public RuleCall getHeritageHeritageParserRuleCall_4_2_0() { return cHeritageHeritageParserRuleCall_4_2_0; }
		
		//("," heritage+=Heritage)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//heritage+=Heritage
		public Assignment getHeritageAssignment_4_3_1() { return cHeritageAssignment_4_3_1; }
		
		//Heritage
		public RuleCall getHeritageHeritageParserRuleCall_4_3_1_0() { return cHeritageHeritageParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//('class' '{' class+=Class ("," class+=Class)* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'class'
		public Keyword getClassKeyword_5_0() { return cClassKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//class+=Class
		public Assignment getClassAssignment_5_2() { return cClassAssignment_5_2; }
		
		//Class
		public RuleCall getClassClassParserRuleCall_5_2_0() { return cClassClassParserRuleCall_5_2_0; }
		
		//("," class+=Class)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//class+=Class
		public Assignment getClassAssignment_5_3_1() { return cClassAssignment_5_3_1; }
		
		//Class
		public RuleCall getClassClassParserRuleCall_5_3_1_0() { return cClassClassParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class TypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUML.Type");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cType_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cFloatParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cInt0ParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cBooleanParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cString0ParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//Type:
		//	Type_Impl | Float | Int0 | Boolean | String0;
		@Override public ParserRule getRule() { return rule; }
		
		//Type_Impl | Float | Int0 | Boolean | String0
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Type_Impl
		public RuleCall getType_ImplParserRuleCall_0() { return cType_ImplParserRuleCall_0; }
		
		//Float
		public RuleCall getFloatParserRuleCall_1() { return cFloatParserRuleCall_1; }
		
		//Int0
		public RuleCall getInt0ParserRuleCall_2() { return cInt0ParserRuleCall_2; }
		
		//Boolean
		public RuleCall getBooleanParserRuleCall_3() { return cBooleanParserRuleCall_3; }
		
		//String0
		public RuleCall getString0ParserRuleCall_4() { return cString0ParserRuleCall_4; }
	}
	public class AssociationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUML.Association");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAssociationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cUsedKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cUsedAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cUsedRoleParserRuleCall_4_0 = (RuleCall)cUsedAssignment_4.eContents().get(0);
		private final Keyword cUserKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cUserAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cUserRoleParserRuleCall_6_0 = (RuleCall)cUserAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Association:
		//	'Association'
		//	name=EString
		//	'{'
		//	'used' used=Role
		//	'user' user=Role
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Association' name=EString '{' 'used' used=Role 'user' user=Role '}'
		public Group getGroup() { return cGroup; }
		
		//'Association'
		public Keyword getAssociationKeyword_0() { return cAssociationKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'used'
		public Keyword getUsedKeyword_3() { return cUsedKeyword_3; }
		
		//used=Role
		public Assignment getUsedAssignment_4() { return cUsedAssignment_4; }
		
		//Role
		public RuleCall getUsedRoleParserRuleCall_4_0() { return cUsedRoleParserRuleCall_4_0; }
		
		//'user'
		public Keyword getUserKeyword_5() { return cUserKeyword_5; }
		
		//user=Role
		public Assignment getUserAssignment_6() { return cUserAssignment_6; }
		
		//Role
		public RuleCall getUserRoleParserRuleCall_6_0() { return cUserRoleParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class HeritageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUML.Heritage");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHeritageKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cMotherKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cMotherAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cMotherRoleParserRuleCall_4_0 = (RuleCall)cMotherAssignment_4.eContents().get(0);
		private final Keyword cChildKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cChildAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cChildRoleParserRuleCall_6_0 = (RuleCall)cChildAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Heritage:
		//	'Heritage'
		//	name=EString
		//	'{'
		//	'mother' mother=Role
		//	'child' child=Role
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Heritage' name=EString '{' 'mother' mother=Role 'child' child=Role '}'
		public Group getGroup() { return cGroup; }
		
		//'Heritage'
		public Keyword getHeritageKeyword_0() { return cHeritageKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'mother'
		public Keyword getMotherKeyword_3() { return cMotherKeyword_3; }
		
		//mother=Role
		public Assignment getMotherAssignment_4() { return cMotherAssignment_4; }
		
		//Role
		public RuleCall getMotherRoleParserRuleCall_4_0() { return cMotherRoleParserRuleCall_4_0; }
		
		//'child'
		public Keyword getChildKeyword_5() { return cChildKeyword_5; }
		
		//child=Role
		public Assignment getChildAssignment_6() { return cChildAssignment_6; }
		
		//Role
		public RuleCall getChildRoleParserRuleCall_6_0() { return cChildRoleParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class ClassElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUML.Class");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cClassAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cClassKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cMethodKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cMethodAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cMethodMethodParserRuleCall_4_2_0 = (RuleCall)cMethodAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cMethodAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cMethodMethodParserRuleCall_4_3_1_0 = (RuleCall)cMethodAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cAttributeKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cAttributeAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cAttributeTypeParserRuleCall_5_2_0 = (RuleCall)cAttributeAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cAttributeAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cAttributeTypeParserRuleCall_5_3_1_0 = (RuleCall)cAttributeAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Class:
		//	{Class}
		//	'Class'
		//	name=EString
		//	'{' ('method' '{' method+=Method ("," method+=Method)* '}')? ('attribute' '{' attribute+=Type ("," attribute+=Type)*
		//	'}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Class} 'Class' name=EString '{' ('method' '{' method+=Method ("," method+=Method)* '}')? ('attribute' '{'
		//attribute+=Type ("," attribute+=Type)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{Class}
		public Action getClassAction_0() { return cClassAction_0; }
		
		//'Class'
		public Keyword getClassKeyword_1() { return cClassKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('method' '{' method+=Method ("," method+=Method)* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'method'
		public Keyword getMethodKeyword_4_0() { return cMethodKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//method+=Method
		public Assignment getMethodAssignment_4_2() { return cMethodAssignment_4_2; }
		
		//Method
		public RuleCall getMethodMethodParserRuleCall_4_2_0() { return cMethodMethodParserRuleCall_4_2_0; }
		
		//("," method+=Method)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//method+=Method
		public Assignment getMethodAssignment_4_3_1() { return cMethodAssignment_4_3_1; }
		
		//Method
		public RuleCall getMethodMethodParserRuleCall_4_3_1_0() { return cMethodMethodParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//('attribute' '{' attribute+=Type ("," attribute+=Type)* '}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'attribute'
		public Keyword getAttributeKeyword_5_0() { return cAttributeKeyword_5_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }
		
		//attribute+=Type
		public Assignment getAttributeAssignment_5_2() { return cAttributeAssignment_5_2; }
		
		//Type
		public RuleCall getAttributeTypeParserRuleCall_5_2_0() { return cAttributeTypeParserRuleCall_5_2_0; }
		
		//("," attribute+=Type)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//attribute+=Type
		public Assignment getAttributeAssignment_5_3_1() { return cAttributeAssignment_5_3_1; }
		
		//Type
		public RuleCall getAttributeTypeParserRuleCall_5_3_1_0() { return cAttributeTypeParserRuleCall_5_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUML.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class RoleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUML.Role");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRoleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cUpperKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cUpperAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cUpperEIntParserRuleCall_4_0 = (RuleCall)cUpperAssignment_4.eContents().get(0);
		private final Keyword cLowerKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cLowerAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cLowerEIntParserRuleCall_6_0 = (RuleCall)cLowerAssignment_6.eContents().get(0);
		private final Keyword cClassKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cClassAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cClassClassParserRuleCall_8_0 = (RuleCall)cClassAssignment_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Role:
		//	'Role'
		//	name=EString
		//	'{'
		//	'upper' upper=EInt
		//	'lower' lower=EInt
		//	'class' class=Class
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Role' name=EString '{' 'upper' upper=EInt 'lower' lower=EInt 'class' class=Class '}'
		public Group getGroup() { return cGroup; }
		
		//'Role'
		public Keyword getRoleKeyword_0() { return cRoleKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'upper'
		public Keyword getUpperKeyword_3() { return cUpperKeyword_3; }
		
		//upper=EInt
		public Assignment getUpperAssignment_4() { return cUpperAssignment_4; }
		
		//EInt
		public RuleCall getUpperEIntParserRuleCall_4_0() { return cUpperEIntParserRuleCall_4_0; }
		
		//'lower'
		public Keyword getLowerKeyword_5() { return cLowerKeyword_5; }
		
		//lower=EInt
		public Assignment getLowerAssignment_6() { return cLowerAssignment_6; }
		
		//EInt
		public RuleCall getLowerEIntParserRuleCall_6_0() { return cLowerEIntParserRuleCall_6_0; }
		
		//'class'
		public Keyword getClassKeyword_7() { return cClassKeyword_7; }
		
		//class=Class
		public Assignment getClassAssignment_8() { return cClassAssignment_8; }
		
		//Class
		public RuleCall getClassClassParserRuleCall_8_0() { return cClassClassParserRuleCall_8_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUML.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt ecore::EInt:
		//	'-'? INT
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class MethodElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUML.Method");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cMethodAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cMethodKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cParametersKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cParametersAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cParametersTypeParserRuleCall_4_2_0 = (RuleCall)cParametersAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cParametersAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cParametersTypeParserRuleCall_4_3_1_0 = (RuleCall)cParametersAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cReturnKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cReturnAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cReturnTypeParserRuleCall_5_1_0 = (RuleCall)cReturnAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Method:
		//	{Method}
		//	'Method'
		//	name=EString
		//	'{' ('parameters' '{' parameters+=Type ("," parameters+=Type)* '}')? ('return' return=Type)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Method} 'Method' name=EString '{' ('parameters' '{' parameters+=Type ("," parameters+=Type)* '}')? ('return'
		//return=Type)? '}'
		public Group getGroup() { return cGroup; }
		
		//{Method}
		public Action getMethodAction_0() { return cMethodAction_0; }
		
		//'Method'
		public Keyword getMethodKeyword_1() { return cMethodKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('parameters' '{' parameters+=Type ("," parameters+=Type)* '}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'parameters'
		public Keyword getParametersKeyword_4_0() { return cParametersKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//parameters+=Type
		public Assignment getParametersAssignment_4_2() { return cParametersAssignment_4_2; }
		
		//Type
		public RuleCall getParametersTypeParserRuleCall_4_2_0() { return cParametersTypeParserRuleCall_4_2_0; }
		
		//("," parameters+=Type)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//parameters+=Type
		public Assignment getParametersAssignment_4_3_1() { return cParametersAssignment_4_3_1; }
		
		//Type
		public RuleCall getParametersTypeParserRuleCall_4_3_1_0() { return cParametersTypeParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//('return' return=Type)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'return'
		public Keyword getReturnKeyword_5_0() { return cReturnKeyword_5_0; }
		
		//return=Type
		public Assignment getReturnAssignment_5_1() { return cReturnAssignment_5_1; }
		
		//Type
		public RuleCall getReturnTypeParserRuleCall_5_1_0() { return cReturnTypeParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class Type_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUML.Type_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTypeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTypeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//Type_Impl Type:
		//	{Type}
		//	'Type'
		//	name=EString
		@Override public ParserRule getRule() { return rule; }
		
		//{Type} 'Type' name=EString
		public Group getGroup() { return cGroup; }
		
		//{Type}
		public Action getTypeAction_0() { return cTypeAction_0; }
		
		//'Type'
		public Keyword getTypeKeyword_1() { return cTypeKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class FloatElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUML.Float");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cFloatAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFloatKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//Float:
		//	{Float}
		//	'Float'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{Float} 'Float' name=EString
		public Group getGroup() { return cGroup; }
		
		//{Float}
		public Action getFloatAction_0() { return cFloatAction_0; }
		
		//'Float'
		public Keyword getFloatKeyword_1() { return cFloatKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class Int0Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUML.Int0");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cIntAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cIntKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//Int0 Int:
		//	{Int}
		//	'Int'
		//	name=EString
		@Override public ParserRule getRule() { return rule; }
		
		//{Int} 'Int' name=EString
		public Group getGroup() { return cGroup; }
		
		//{Int}
		public Action getIntAction_0() { return cIntAction_0; }
		
		//'Int'
		public Keyword getIntKeyword_1() { return cIntKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class BooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUML.Boolean");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBooleanAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cBooleanKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//Boolean:
		//	{Boolean}
		//	'Boolean'
		//	name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//{Boolean} 'Boolean' name=EString
		public Group getGroup() { return cGroup; }
		
		//{Boolean}
		public Action getBooleanAction_0() { return cBooleanAction_0; }
		
		//'Boolean'
		public Keyword getBooleanKeyword_1() { return cBooleanKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	public class String0Elements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.smalluml.SmallUML.String0");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cStringAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cStringKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//String0 String:
		//	{String}
		//	'String'
		//	name=EString
		@Override public ParserRule getRule() { return rule; }
		
		//{String} 'String' name=EString
		public Group getGroup() { return cGroup; }
		
		//{String}
		public Action getStringAction_0() { return cStringAction_0; }
		
		//'String'
		public Keyword getStringKeyword_1() { return cStringKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	
	
	private final DiagramElements pDiagram;
	private final TypeElements pType;
	private final AssociationElements pAssociation;
	private final HeritageElements pHeritage;
	private final ClassElements pClass;
	private final EStringElements pEString;
	private final RoleElements pRole;
	private final EIntElements pEInt;
	private final MethodElements pMethod;
	private final Type_ImplElements pType_Impl;
	private final FloatElements pFloat;
	private final Int0Elements pInt0;
	private final BooleanElements pBoolean;
	private final String0Elements pString0;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public SmallUMLGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pDiagram = new DiagramElements();
		this.pType = new TypeElements();
		this.pAssociation = new AssociationElements();
		this.pHeritage = new HeritageElements();
		this.pClass = new ClassElements();
		this.pEString = new EStringElements();
		this.pRole = new RoleElements();
		this.pEInt = new EIntElements();
		this.pMethod = new MethodElements();
		this.pType_Impl = new Type_ImplElements();
		this.pFloat = new FloatElements();
		this.pInt0 = new Int0Elements();
		this.pBoolean = new BooleanElements();
		this.pString0 = new String0Elements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.smalluml.SmallUML".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Diagram:
	//	{Diagram}
	//	'Diagram'
	//	'{' ('assoc' '{' assoc+=Association ("," assoc+=Association)* '}')? ('heritage' '{' heritage+=Heritage (","
	//	heritage+=Heritage)* '}')? ('class' '{' class+=Class ("," class+=Class)* '}')?
	//	'}';
	public DiagramElements getDiagramAccess() {
		return pDiagram;
	}
	
	public ParserRule getDiagramRule() {
		return getDiagramAccess().getRule();
	}
	
	//Type:
	//	Type_Impl | Float | Int0 | Boolean | String0;
	public TypeElements getTypeAccess() {
		return pType;
	}
	
	public ParserRule getTypeRule() {
		return getTypeAccess().getRule();
	}
	
	//Association:
	//	'Association'
	//	name=EString
	//	'{'
	//	'used' used=Role
	//	'user' user=Role
	//	'}';
	public AssociationElements getAssociationAccess() {
		return pAssociation;
	}
	
	public ParserRule getAssociationRule() {
		return getAssociationAccess().getRule();
	}
	
	//Heritage:
	//	'Heritage'
	//	name=EString
	//	'{'
	//	'mother' mother=Role
	//	'child' child=Role
	//	'}';
	public HeritageElements getHeritageAccess() {
		return pHeritage;
	}
	
	public ParserRule getHeritageRule() {
		return getHeritageAccess().getRule();
	}
	
	//Class:
	//	{Class}
	//	'Class'
	//	name=EString
	//	'{' ('method' '{' method+=Method ("," method+=Method)* '}')? ('attribute' '{' attribute+=Type ("," attribute+=Type)*
	//	'}')?
	//	'}';
	public ClassElements getClassAccess() {
		return pClass;
	}
	
	public ParserRule getClassRule() {
		return getClassAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Role:
	//	'Role'
	//	name=EString
	//	'{'
	//	'upper' upper=EInt
	//	'lower' lower=EInt
	//	'class' class=Class
	//	'}';
	public RoleElements getRoleAccess() {
		return pRole;
	}
	
	public ParserRule getRoleRule() {
		return getRoleAccess().getRule();
	}
	
	//EInt ecore::EInt:
	//	'-'? INT
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//Method:
	//	{Method}
	//	'Method'
	//	name=EString
	//	'{' ('parameters' '{' parameters+=Type ("," parameters+=Type)* '}')? ('return' return=Type)?
	//	'}';
	public MethodElements getMethodAccess() {
		return pMethod;
	}
	
	public ParserRule getMethodRule() {
		return getMethodAccess().getRule();
	}
	
	//Type_Impl Type:
	//	{Type}
	//	'Type'
	//	name=EString
	public Type_ImplElements getType_ImplAccess() {
		return pType_Impl;
	}
	
	public ParserRule getType_ImplRule() {
		return getType_ImplAccess().getRule();
	}
	
	//Float:
	//	{Float}
	//	'Float'
	//	name=EString;
	public FloatElements getFloatAccess() {
		return pFloat;
	}
	
	public ParserRule getFloatRule() {
		return getFloatAccess().getRule();
	}
	
	//Int0 Int:
	//	{Int}
	//	'Int'
	//	name=EString
	public Int0Elements getInt0Access() {
		return pInt0;
	}
	
	public ParserRule getInt0Rule() {
		return getInt0Access().getRule();
	}
	
	//Boolean:
	//	{Boolean}
	//	'Boolean'
	//	name=EString;
	public BooleanElements getBooleanAccess() {
		return pBoolean;
	}
	
	public ParserRule getBooleanRule() {
		return getBooleanAccess().getRule();
	}
	
	//String0 String:
	//	{String}
	//	'String'
	//	name=EString
	public String0Elements getString0Access() {
		return pString0;
	}
	
	public ParserRule getString0Rule() {
		return getString0Access().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/ *'->'* /';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
